### ISSUE TITLE
irrelevant comments

### ISSUE THREAD

**Issue by WladimirSidorenko** [jacobeisenstein/unix-sociolinguistics#1]
As a former shell worshipper, I will occasionally comment on some stuff, if you don't mind. (close the issue if you do)

1) using

``````
    ```shell
    ```
``````

might help you get better highlighting in markdown, e.g.:

``` shell
echo 'Hello world'
```

2)  You can use `head -1` and `tail -1` without providing the `-n` option;

3) Beware of pipes. Errors thrown in intermediate processing steps will not be seen at the end (only the exit status of the last command is typically returned), e.g.:

``` shell
echo hui | false | true ; echo $?
0
```

If you are using `bash`, invoking `set -o pipefail` at the very beginning of the interactive session or putting it into your `.bashrc` might be helpful (though it might disturb sometime), e.g.:

``` shell
set -o pipefail
echo hui | false | true ; echo $?
1
```

4) Don't use double quotes unless you explicitly need them.  Text included into double quotes gets processed by the shell -- you don't need it most of the time:

``` shell
echo "$$"
2615

echo '$$'
$$
```

5) `sort` provides the `-u` option for doing `uniq` in the same step, so you can save some typing;

6) `for gender in {'M','F'}` -- you are either lucky or very proficient.  I think, until `bash 4.0`, this kind of iteration was not supported by shells -- old-school guys still use the simple form `for gender in M F`

P.S.
@students the above comments are just smallish optimizations so you should trust your professor -- he is good and is teaching you right things

@jacobeisenstein this is neither criticism nor a way to boast (You don't need the first thing, I don't need the second).  As the title suggests, these are only irrelevant comments.  Consider it as a mumble to myself and close this issue, if you don't want to hear that mumble.

**Comment by jacobeisenstein** [comment]
Great comments, thanks! I've incorporated most of them.

**Comment by WladimirSidorenko** [comment]
Thank you, @jacobeisenstein. I'm really very glad that these comments could be helpful somehow.

Here are a few more remarks, which are actually just side notes:

1) `grep -E` is equivalent to `egrep`;

2) with `egrep '^[A-Za-z]'`, one might get into trouble when the processed text is not in plain ASCII, e.g.:

``` shell
echo 'äquivalent' | LC_ALL=C egrep '^[A-Za-z]'

echo 'äquivalent' | LC_ALL=C.UTF-8 egrep '^[A-Za-z]'
```

Again, bearded Unix guys in holey sweaters would prefer `[[:alpha:]]` in this case:

``` shell
echo 'äquivalent' | LC_ALL=C egrep '^[[:alpha:]]'

echo 'äquivalent' | LC_ALL=C.UTF-8 egrep '^[[:alpha:]]'
äquivalent
```

**Comment by WladimirSidorenko** [comment]
I'll probably open another issue if there will be any updates and I'll have anything to say.  At the moment, there seems to be no need for this issue hanging around.
